package com.cioc.mygreendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cioc.mygreendao.db.GPSLocation;

import com.cioc.mygreendao.db.GPSLocationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gPSLocationDaoConfig;

    private final GPSLocationDao gPSLocationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gPSLocationDaoConfig = daoConfigMap.get(GPSLocationDao.class).clone();
        gPSLocationDaoConfig.initIdentityScope(type);

        gPSLocationDao = new GPSLocationDao(gPSLocationDaoConfig, this);

        registerDao(GPSLocation.class, gPSLocationDao);
    }
    
    public void clear() {
        gPSLocationDaoConfig.clearIdentityScope();
    }

    public GPSLocationDao getGPSLocationDao() {
        return gPSLocationDao;
    }

}
