package com.cioc.mygreendao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GPSLOCATION".
*/
public class GPSLocationDao extends AbstractDao<GPSLocation, Long> {

    public static final String TABLENAME = "GPSLOCATION";

    /**
     * Properties of entity GPSLocation.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Longitude_value = new Property(1, String.class, "longitude_value", false, "LONGITUDE_VALUE");
        public final static Property Latitude_value = new Property(2, String.class, "latitude_value", false, "LATITUDE_VALUE");
        public final static Property Date_time = new Property(3, String.class, "date_time", false, "DATE_TIME");
    }


    public GPSLocationDao(DaoConfig config) {
        super(config);
    }
    
    public GPSLocationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GPSLOCATION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"LONGITUDE_VALUE\" TEXT," + // 1: longitude_value
                "\"LATITUDE_VALUE\" TEXT," + // 2: latitude_value
                "\"DATE_TIME\" TEXT);"); // 3: date_time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GPSLOCATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GPSLocation entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String longitude_value = entity.getLongitude_value();
        if (longitude_value != null) {
            stmt.bindString(2, longitude_value);
        }
 
        String latitude_value = entity.getLatitude_value();
        if (latitude_value != null) {
            stmt.bindString(3, latitude_value);
        }
 
        String date_time = entity.getDate_time();
        if (date_time != null) {
            stmt.bindString(4, date_time);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GPSLocation entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String longitude_value = entity.getLongitude_value();
        if (longitude_value != null) {
            stmt.bindString(2, longitude_value);
        }
 
        String latitude_value = entity.getLatitude_value();
        if (latitude_value != null) {
            stmt.bindString(3, latitude_value);
        }
 
        String date_time = entity.getDate_time();
        if (date_time != null) {
            stmt.bindString(4, date_time);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GPSLocation readEntity(Cursor cursor, int offset) {
        GPSLocation entity = new GPSLocation( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // longitude_value
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // latitude_value
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // date_time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GPSLocation entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLongitude_value(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLatitude_value(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDate_time(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GPSLocation entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GPSLocation entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GPSLocation entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
