package com.cioc.mygreendao.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "GPSLOCATION".
 */
@Entity
public class GPSLocation {

    @Id(autoincrement = true)
    private Long id;
    private String longitude_value;
    private String latitude_value;
    private String date_time;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public GPSLocation() {
    }

    public GPSLocation(Long id) {
        this.id = id;
    }

    @Generated
    public GPSLocation(Long id, String longitude_value, String latitude_value, String date_time) {
        this.id = id;
        this.longitude_value = longitude_value;
        this.latitude_value = latitude_value;
        this.date_time = date_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLongitude_value() {
        return longitude_value;
    }

    public void setLongitude_value(String longitude_value) {
        this.longitude_value = longitude_value;
    }

    public String getLatitude_value() {
        return latitude_value;
    }

    public void setLatitude_value(String latitude_value) {
        this.latitude_value = latitude_value;
    }

    public String getDate_time() {
        return date_time;
    }

    public void setDate_time(String date_time) {
        this.date_time = date_time;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
